---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: PlatformAdmin
rules:
  - apiGroups: [""]
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/attach
      - pods/exec
      - pods/log
      - pods/portforward
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - serviceaccounts
      - services
      - services/proxy
    verbs: ["*"]
  
  - apiGroups:    
      - admissionregistration.k8s.io
      - apiextensions.k8s.io
      - apiregistration.k8s.io
      - apps
      - authentication.k8s.io
      - authorization.k8s.io
      - autoscaling
      - batch
      - certificates.k8s.io
      - coordination.k8s.io
      - discovery.k8s.io
      - events.k8s.io
      - flowcontrol.apiserver.k8s.io
      - networking.k8s.io
      - node.k8s.io
      - policy
      - rbac.authorization.k8s.io
      - resource.k8s.io
      - scheduling.k8s.io
      - storage.k8s.io
    resources: ["*"]
    verbs: ["*"]

  - nonResourceURLs: ["*"]
    verbs: ["*"]
