---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: AppDev
  namespace: team-a
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
    verbs: ["get","list","watch","create","update","patch","delete"]
      
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
    verbs: ["get","list","watch","create","update","patch","delete"]
