---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-platformadmin
  namespace: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-appdev
  namespace: team-a

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-auditor
  namespace: default
